# Generated by Django 4.2.3 on 2023-08-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('origin', models.CharField(max_length=100)),
                ('flavour', models.CharField(max_length=100)),
                ('roast', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('D', 'Dark')], default='L', max_length=1)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
