# Generated by Django 4.2.3 on 2023-08-06 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_order_orderitem'),
        ('main_app', '0002_product_user'),
    ]

    operations = [
    ]
