# Generated by Django 4.2.3 on 2023-08-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_merge_0002_order_orderitem_0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='order date'),
        ),
    ]
