# Generated by Django 4.2.3 on 2023-08-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'Cart'), ('P', 'Paid'), ('S', 'Shipped'), ('D', 'Delivered')], default='C', max_length=1),
        ),
    ]
